artifact_location: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/597781592236048130
creation_time: 1776860585313
experiment_id: '597781592236048130'
last_update_time: 1776860585313
lifecycle_stage: active
name: Interval Scheduling
