artifact_uri: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/181114269738768505/4c7e4ccb205d4825aadf7b9d78d4783f/artifacts
end_time: 1777641217862
entry_point_name: ''
experiment_id: '181114269738768505'
lifecycle_stage: active
run_id: 4c7e4ccb205d4825aadf7b9d78d4783f
run_name: mpc_det_rule_constGrid_freq-60_building-SFH4
source_name: ''
source_type: 4
source_version: ''
start_time: 1777641214703
status: 3
tags: []
user_id: farazfirouzbakht
