artifact_uri: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/597781592236048130/e3eac2f95bf542bab445cd4eef016f23/artifacts
end_time: 1777290675275
entry_point_name: ''
experiment_id: '597781592236048130'
lifecycle_stage: active
run_id: e3eac2f95bf542bab445cd4eef016f23
run_name: batch_2026-04-27_13-50
source_name: ''
source_type: 4
source_version: ''
start_time: 1777290656245
status: 3
tags: []
user_id: farazfirouzbakht
