artifact_uri: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/597781592236048130/400cec9d295646d88439a7c49d365e01/artifacts
end_time: 1777289471788
entry_point_name: ''
experiment_id: '597781592236048130'
lifecycle_stage: active
run_id: 400cec9d295646d88439a7c49d365e01
run_name: ideal_rule_constGrid_freq-60_building-SFH3
source_name: ''
source_type: 4
source_version: ''
start_time: 1777289416204
status: 4
tags: []
user_id: farazfirouzbakht
