artifact_uri: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/609520425598582801/81f2c8495f4d42a4836733d29df486e4/artifacts
end_time: 1777903900153
entry_point_name: ''
experiment_id: '609520425598582801'
lifecycle_stage: active
run_id: 81f2c8495f4d42a4836733d29df486e4
run_name: ideal_freq-15_building-SFH4
source_name: ''
source_type: 4
source_version: ''
start_time: 1777903597777
status: 3
tags: []
user_id: farazfirouzbakht
