artifact_uri: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/597781592236048130/2b0ee9745c104856ab10783a2f1080aa/artifacts
end_time: 1777290675239
entry_point_name: ''
experiment_id: '597781592236048130'
lifecycle_stage: active
run_id: 2b0ee9745c104856ab10783a2f1080aa
run_name: mpc_det_rule_constGrid_freq-60_building-SFH3
source_name: ''
source_type: 4
source_version: ''
start_time: 1777290656904
status: 3
tags: []
user_id: farazfirouzbakht
