artifact_location: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/181114269738768505
creation_time: 1777293032476
experiment_id: '181114269738768505'
last_update_time: 1777293032476
lifecycle_stage: active
name: MPC_10sec_Challenge
