artifact_location: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/0
creation_time: 1776860585307
experiment_id: '0'
last_update_time: 1776860585307
lifecycle_stage: active
name: Default
