artifact_uri: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/181114269738768505/56b8762c771d4ccb9d88618ccf2d3174/artifacts
end_time: 1777299399382
entry_point_name: ''
experiment_id: '181114269738768505'
lifecycle_stage: active
run_id: 56b8762c771d4ccb9d88618ccf2d3174
run_name: mpc_det_rule_constGrid_freq-60_building-SFH3
source_name: ''
source_type: 4
source_version: ''
start_time: 1777299396630
status: 3
tags: []
user_id: farazfirouzbakht
