artifact_uri: file:///Users/farazfirouzbakht/Desktop/Programming/MPC-vs-RBC/MPC-vs-RBC/mlruns/597781592236048130/f5bf893533d941d0b77ed6e461afead0/artifacts
end_time: 1777289471791
entry_point_name: ''
experiment_id: '597781592236048130'
lifecycle_stage: active
run_id: f5bf893533d941d0b77ed6e461afead0
run_name: batch_2026-04-27_13-22
source_name: ''
source_type: 4
source_version: ''
start_time: 1777288961808
status: 4
tags: []
user_id: farazfirouzbakht
